{
  imports = [
    ./dave.nix
    ./fail2ban.nix
    ./forgejo.nix
    ./nfs-server.nix
    ./nginx
    ./nix-serve.nix
    ./samba.nix
    ./snapserver.nix
    #./paperless.nix
    ./podman
    ./postgresql.nix
    ./jellyfin.nix
    ./transmission.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
  ];
}
